<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "exposition_mnp"
 *
 * Auto generated by Extension Builder 2018-06-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'exposition_mnp',
    'description' => 'projet dawin exposition par:
-Alban MILANT
-Sébastien NOEL
-Rémi PACHET',
    'category' => 'plugin',
    'author' => 'Alban MILANT, Sébastien NOEL, Rémi PACHET',
    'author_email' => 'alban.milant@hotmail.fr, sebastien.noel.pro@gmail.com, remipachet@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
